# Generated by Django 2.2.3 on 2019-07-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(help_text='Enter your bio details here.', max_length=20000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter your blog text here.', max_length=20000),
        ),
    ]
